version: 1

labels:
- label: "documentation"
  files:
    - "README.md"

- label: "documentation"
  files:
    - "docs/.*"

- label: "tests"
  files:
    - "tests/.*"

- label: "CMake"
  files:
    - ".*CMakeLists.txt"

- label: "CMake"
  files:
    - "cmake/.*"

- label: "CI"
  files:
    - ".github/workflows/.*"

- label: "CI"
  files:
    - ".github/external_ci/.*"

- label: "CI"
  files:
    - ".github/(dependabot|labeler)\\.yml"

- label: "aspect: binary formats"
  files:
    - "include/nlohmann/detail/input/binary_reader\\.hpp"
    - "include/nlohmann/detail/output/binary_writer\\.hpp"
    - "tests/src/unit-(bson|cbor|msgpack|ubjson|bjdata|binary_formats)"
    - "tests/src/fuzzer-parse_(bson|cbor|msgpack|ubjson|bjdata)"
    - "docs/mkdocs/docs/features/binary_formats/"
    - "docs/mkdocs/docs/(api/basic_json|examples)/(to|from)_(bson|cbor|msgpack|ubjson|bjdata)"

- label: "aspect: binary formats"
  title: "(?i)(bson|cbor|msgpack|messagepack|ubjson|bjdata|binary format)"

- label: "python"
  files:
    - "\\.py$"
    - "requirements[^/]*\\.txt$"

- label: "S"
  size-below: 10
- label: "M"
  size-above: 9
  size-below: 100
- label: "L"
  size-above: 100
