# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lucapassarella/Documents/projects/json

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lucapassarella/Documents/projects/json

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.24.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucapassarella/Documents/projects/json/CMakeFiles /Users/lucapassarella/Documents/projects/json//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucapassarella/Documents/projects/json/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named download_test_data

# Build rule for target.
download_test_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 download_test_data
.PHONY : download_test_data

# fast build rule for target.
download_test_data/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/download_test_data.dir/build.make test/CMakeFiles/download_test_data.dir/build
.PHONY : download_test_data/fast

#=============================================================================
# Target rules for targets named test_main

# Build rule for target.
test_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_main
.PHONY : test_main

# fast build rule for target.
test_main/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_main.dir/build.make test/CMakeFiles/test_main.dir/build
.PHONY : test_main/fast

#=============================================================================
# Target rules for targets named test-algorithms_cpp11

# Build rule for target.
test-algorithms_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-algorithms_cpp11
.PHONY : test-algorithms_cpp11

# fast build rule for target.
test-algorithms_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-algorithms_cpp11.dir/build.make test/CMakeFiles/test-algorithms_cpp11.dir/build
.PHONY : test-algorithms_cpp11/fast

#=============================================================================
# Target rules for targets named test-allocator_cpp11

# Build rule for target.
test-allocator_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-allocator_cpp11
.PHONY : test-allocator_cpp11

# fast build rule for target.
test-allocator_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-allocator_cpp11.dir/build.make test/CMakeFiles/test-allocator_cpp11.dir/build
.PHONY : test-allocator_cpp11/fast

#=============================================================================
# Target rules for targets named test-alt-string_cpp11

# Build rule for target.
test-alt-string_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-alt-string_cpp11
.PHONY : test-alt-string_cpp11

# fast build rule for target.
test-alt-string_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-alt-string_cpp11.dir/build.make test/CMakeFiles/test-alt-string_cpp11.dir/build
.PHONY : test-alt-string_cpp11/fast

#=============================================================================
# Target rules for targets named test-assert_macro_cpp11

# Build rule for target.
test-assert_macro_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-assert_macro_cpp11
.PHONY : test-assert_macro_cpp11

# fast build rule for target.
test-assert_macro_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-assert_macro_cpp11.dir/build.make test/CMakeFiles/test-assert_macro_cpp11.dir/build
.PHONY : test-assert_macro_cpp11/fast

#=============================================================================
# Target rules for targets named test-bson_cpp11

# Build rule for target.
test-bson_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-bson_cpp11
.PHONY : test-bson_cpp11

# fast build rule for target.
test-bson_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-bson_cpp11.dir/build.make test/CMakeFiles/test-bson_cpp11.dir/build
.PHONY : test-bson_cpp11/fast

#=============================================================================
# Target rules for targets named test-byte_container_with_subtype_cpp11

# Build rule for target.
test-byte_container_with_subtype_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-byte_container_with_subtype_cpp11
.PHONY : test-byte_container_with_subtype_cpp11

# fast build rule for target.
test-byte_container_with_subtype_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-byte_container_with_subtype_cpp11.dir/build.make test/CMakeFiles/test-byte_container_with_subtype_cpp11.dir/build
.PHONY : test-byte_container_with_subtype_cpp11/fast

#=============================================================================
# Target rules for targets named test-capacity_cpp11

# Build rule for target.
test-capacity_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-capacity_cpp11
.PHONY : test-capacity_cpp11

# fast build rule for target.
test-capacity_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-capacity_cpp11.dir/build.make test/CMakeFiles/test-capacity_cpp11.dir/build
.PHONY : test-capacity_cpp11/fast

#=============================================================================
# Target rules for targets named test-cbor_cpp11

# Build rule for target.
test-cbor_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-cbor_cpp11
.PHONY : test-cbor_cpp11

# fast build rule for target.
test-cbor_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-cbor_cpp11.dir/build.make test/CMakeFiles/test-cbor_cpp11.dir/build
.PHONY : test-cbor_cpp11/fast

#=============================================================================
# Target rules for targets named test-class_const_iterator_cpp11

# Build rule for target.
test-class_const_iterator_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-class_const_iterator_cpp11
.PHONY : test-class_const_iterator_cpp11

# fast build rule for target.
test-class_const_iterator_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-class_const_iterator_cpp11.dir/build.make test/CMakeFiles/test-class_const_iterator_cpp11.dir/build
.PHONY : test-class_const_iterator_cpp11/fast

#=============================================================================
# Target rules for targets named test-class_iterator_cpp11

# Build rule for target.
test-class_iterator_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-class_iterator_cpp11
.PHONY : test-class_iterator_cpp11

# fast build rule for target.
test-class_iterator_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-class_iterator_cpp11.dir/build.make test/CMakeFiles/test-class_iterator_cpp11.dir/build
.PHONY : test-class_iterator_cpp11/fast

#=============================================================================
# Target rules for targets named test-class_lexer_cpp11

# Build rule for target.
test-class_lexer_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-class_lexer_cpp11
.PHONY : test-class_lexer_cpp11

# fast build rule for target.
test-class_lexer_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-class_lexer_cpp11.dir/build.make test/CMakeFiles/test-class_lexer_cpp11.dir/build
.PHONY : test-class_lexer_cpp11/fast

#=============================================================================
# Target rules for targets named test-class_parser_cpp11

# Build rule for target.
test-class_parser_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-class_parser_cpp11
.PHONY : test-class_parser_cpp11

# fast build rule for target.
test-class_parser_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-class_parser_cpp11.dir/build.make test/CMakeFiles/test-class_parser_cpp11.dir/build
.PHONY : test-class_parser_cpp11/fast

#=============================================================================
# Target rules for targets named test-comparison_cpp11

# Build rule for target.
test-comparison_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-comparison_cpp11
.PHONY : test-comparison_cpp11

# fast build rule for target.
test-comparison_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-comparison_cpp11.dir/build.make test/CMakeFiles/test-comparison_cpp11.dir/build
.PHONY : test-comparison_cpp11/fast

#=============================================================================
# Target rules for targets named test-comparison_cpp20

# Build rule for target.
test-comparison_cpp20: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-comparison_cpp20
.PHONY : test-comparison_cpp20

# fast build rule for target.
test-comparison_cpp20/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-comparison_cpp20.dir/build.make test/CMakeFiles/test-comparison_cpp20.dir/build
.PHONY : test-comparison_cpp20/fast

#=============================================================================
# Target rules for targets named test-concepts_cpp11

# Build rule for target.
test-concepts_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-concepts_cpp11
.PHONY : test-concepts_cpp11

# fast build rule for target.
test-concepts_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-concepts_cpp11.dir/build.make test/CMakeFiles/test-concepts_cpp11.dir/build
.PHONY : test-concepts_cpp11/fast

#=============================================================================
# Target rules for targets named test-constructor1_cpp11

# Build rule for target.
test-constructor1_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-constructor1_cpp11
.PHONY : test-constructor1_cpp11

# fast build rule for target.
test-constructor1_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-constructor1_cpp11.dir/build.make test/CMakeFiles/test-constructor1_cpp11.dir/build
.PHONY : test-constructor1_cpp11/fast

#=============================================================================
# Target rules for targets named test-constructor2_cpp11

# Build rule for target.
test-constructor2_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-constructor2_cpp11
.PHONY : test-constructor2_cpp11

# fast build rule for target.
test-constructor2_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-constructor2_cpp11.dir/build.make test/CMakeFiles/test-constructor2_cpp11.dir/build
.PHONY : test-constructor2_cpp11/fast

#=============================================================================
# Target rules for targets named test-convenience_cpp11

# Build rule for target.
test-convenience_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-convenience_cpp11
.PHONY : test-convenience_cpp11

# fast build rule for target.
test-convenience_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-convenience_cpp11.dir/build.make test/CMakeFiles/test-convenience_cpp11.dir/build
.PHONY : test-convenience_cpp11/fast

#=============================================================================
# Target rules for targets named test-conversions_cpp11

# Build rule for target.
test-conversions_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-conversions_cpp11
.PHONY : test-conversions_cpp11

# fast build rule for target.
test-conversions_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-conversions_cpp11.dir/build.make test/CMakeFiles/test-conversions_cpp11.dir/build
.PHONY : test-conversions_cpp11/fast

#=============================================================================
# Target rules for targets named test-conversions_cpp14

# Build rule for target.
test-conversions_cpp14: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-conversions_cpp14
.PHONY : test-conversions_cpp14

# fast build rule for target.
test-conversions_cpp14/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-conversions_cpp14.dir/build.make test/CMakeFiles/test-conversions_cpp14.dir/build
.PHONY : test-conversions_cpp14/fast

#=============================================================================
# Target rules for targets named test-conversions_cpp17

# Build rule for target.
test-conversions_cpp17: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-conversions_cpp17
.PHONY : test-conversions_cpp17

# fast build rule for target.
test-conversions_cpp17/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-conversions_cpp17.dir/build.make test/CMakeFiles/test-conversions_cpp17.dir/build
.PHONY : test-conversions_cpp17/fast

#=============================================================================
# Target rules for targets named test-deserialization_cpp11

# Build rule for target.
test-deserialization_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-deserialization_cpp11
.PHONY : test-deserialization_cpp11

# fast build rule for target.
test-deserialization_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-deserialization_cpp11.dir/build.make test/CMakeFiles/test-deserialization_cpp11.dir/build
.PHONY : test-deserialization_cpp11/fast

#=============================================================================
# Target rules for targets named test-diagnostics_cpp11

# Build rule for target.
test-diagnostics_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-diagnostics_cpp11
.PHONY : test-diagnostics_cpp11

# fast build rule for target.
test-diagnostics_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-diagnostics_cpp11.dir/build.make test/CMakeFiles/test-diagnostics_cpp11.dir/build
.PHONY : test-diagnostics_cpp11/fast

#=============================================================================
# Target rules for targets named test-disabled_exceptions_cpp11

# Build rule for target.
test-disabled_exceptions_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-disabled_exceptions_cpp11
.PHONY : test-disabled_exceptions_cpp11

# fast build rule for target.
test-disabled_exceptions_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-disabled_exceptions_cpp11.dir/build.make test/CMakeFiles/test-disabled_exceptions_cpp11.dir/build
.PHONY : test-disabled_exceptions_cpp11/fast

#=============================================================================
# Target rules for targets named test-element_access1_cpp11

# Build rule for target.
test-element_access1_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-element_access1_cpp11
.PHONY : test-element_access1_cpp11

# fast build rule for target.
test-element_access1_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-element_access1_cpp11.dir/build.make test/CMakeFiles/test-element_access1_cpp11.dir/build
.PHONY : test-element_access1_cpp11/fast

#=============================================================================
# Target rules for targets named test-element_access2_cpp11

# Build rule for target.
test-element_access2_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-element_access2_cpp11
.PHONY : test-element_access2_cpp11

# fast build rule for target.
test-element_access2_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-element_access2_cpp11.dir/build.make test/CMakeFiles/test-element_access2_cpp11.dir/build
.PHONY : test-element_access2_cpp11/fast

#=============================================================================
# Target rules for targets named test-hash_cpp11

# Build rule for target.
test-hash_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-hash_cpp11
.PHONY : test-hash_cpp11

# fast build rule for target.
test-hash_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-hash_cpp11.dir/build.make test/CMakeFiles/test-hash_cpp11.dir/build
.PHONY : test-hash_cpp11/fast

#=============================================================================
# Target rules for targets named test-inspection_cpp11

# Build rule for target.
test-inspection_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inspection_cpp11
.PHONY : test-inspection_cpp11

# fast build rule for target.
test-inspection_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-inspection_cpp11.dir/build.make test/CMakeFiles/test-inspection_cpp11.dir/build
.PHONY : test-inspection_cpp11/fast

#=============================================================================
# Target rules for targets named test-items_cpp11

# Build rule for target.
test-items_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-items_cpp11
.PHONY : test-items_cpp11

# fast build rule for target.
test-items_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-items_cpp11.dir/build.make test/CMakeFiles/test-items_cpp11.dir/build
.PHONY : test-items_cpp11/fast

#=============================================================================
# Target rules for targets named test-items_cpp14

# Build rule for target.
test-items_cpp14: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-items_cpp14
.PHONY : test-items_cpp14

# fast build rule for target.
test-items_cpp14/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-items_cpp14.dir/build.make test/CMakeFiles/test-items_cpp14.dir/build
.PHONY : test-items_cpp14/fast

#=============================================================================
# Target rules for targets named test-items_cpp17

# Build rule for target.
test-items_cpp17: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-items_cpp17
.PHONY : test-items_cpp17

# fast build rule for target.
test-items_cpp17/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-items_cpp17.dir/build.make test/CMakeFiles/test-items_cpp17.dir/build
.PHONY : test-items_cpp17/fast

#=============================================================================
# Target rules for targets named test-iterators1_cpp11

# Build rule for target.
test-iterators1_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-iterators1_cpp11
.PHONY : test-iterators1_cpp11

# fast build rule for target.
test-iterators1_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-iterators1_cpp11.dir/build.make test/CMakeFiles/test-iterators1_cpp11.dir/build
.PHONY : test-iterators1_cpp11/fast

#=============================================================================
# Target rules for targets named test-iterators2_cpp11

# Build rule for target.
test-iterators2_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-iterators2_cpp11
.PHONY : test-iterators2_cpp11

# fast build rule for target.
test-iterators2_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-iterators2_cpp11.dir/build.make test/CMakeFiles/test-iterators2_cpp11.dir/build
.PHONY : test-iterators2_cpp11/fast

#=============================================================================
# Target rules for targets named test-json_patch_cpp11

# Build rule for target.
test-json_patch_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-json_patch_cpp11
.PHONY : test-json_patch_cpp11

# fast build rule for target.
test-json_patch_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-json_patch_cpp11.dir/build.make test/CMakeFiles/test-json_patch_cpp11.dir/build
.PHONY : test-json_patch_cpp11/fast

#=============================================================================
# Target rules for targets named test-json_pointer_cpp11

# Build rule for target.
test-json_pointer_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-json_pointer_cpp11
.PHONY : test-json_pointer_cpp11

# fast build rule for target.
test-json_pointer_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-json_pointer_cpp11.dir/build.make test/CMakeFiles/test-json_pointer_cpp11.dir/build
.PHONY : test-json_pointer_cpp11/fast

#=============================================================================
# Target rules for targets named test-large_json_cpp11

# Build rule for target.
test-large_json_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-large_json_cpp11
.PHONY : test-large_json_cpp11

# fast build rule for target.
test-large_json_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-large_json_cpp11.dir/build.make test/CMakeFiles/test-large_json_cpp11.dir/build
.PHONY : test-large_json_cpp11/fast

#=============================================================================
# Target rules for targets named test-merge_patch_cpp11

# Build rule for target.
test-merge_patch_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-merge_patch_cpp11
.PHONY : test-merge_patch_cpp11

# fast build rule for target.
test-merge_patch_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-merge_patch_cpp11.dir/build.make test/CMakeFiles/test-merge_patch_cpp11.dir/build
.PHONY : test-merge_patch_cpp11/fast

#=============================================================================
# Target rules for targets named test-meta_cpp11

# Build rule for target.
test-meta_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-meta_cpp11
.PHONY : test-meta_cpp11

# fast build rule for target.
test-meta_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-meta_cpp11.dir/build.make test/CMakeFiles/test-meta_cpp11.dir/build
.PHONY : test-meta_cpp11/fast

#=============================================================================
# Target rules for targets named test-modifiers_cpp11

# Build rule for target.
test-modifiers_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-modifiers_cpp11
.PHONY : test-modifiers_cpp11

# fast build rule for target.
test-modifiers_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-modifiers_cpp11.dir/build.make test/CMakeFiles/test-modifiers_cpp11.dir/build
.PHONY : test-modifiers_cpp11/fast

#=============================================================================
# Target rules for targets named test-msgpack_cpp11

# Build rule for target.
test-msgpack_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-msgpack_cpp11
.PHONY : test-msgpack_cpp11

# fast build rule for target.
test-msgpack_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-msgpack_cpp11.dir/build.make test/CMakeFiles/test-msgpack_cpp11.dir/build
.PHONY : test-msgpack_cpp11/fast

#=============================================================================
# Target rules for targets named test-noexcept_cpp11

# Build rule for target.
test-noexcept_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-noexcept_cpp11
.PHONY : test-noexcept_cpp11

# fast build rule for target.
test-noexcept_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-noexcept_cpp11.dir/build.make test/CMakeFiles/test-noexcept_cpp11.dir/build
.PHONY : test-noexcept_cpp11/fast

#=============================================================================
# Target rules for targets named test-ordered_json_cpp11

# Build rule for target.
test-ordered_json_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-ordered_json_cpp11
.PHONY : test-ordered_json_cpp11

# fast build rule for target.
test-ordered_json_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-ordered_json_cpp11.dir/build.make test/CMakeFiles/test-ordered_json_cpp11.dir/build
.PHONY : test-ordered_json_cpp11/fast

#=============================================================================
# Target rules for targets named test-ordered_map_cpp11

# Build rule for target.
test-ordered_map_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-ordered_map_cpp11
.PHONY : test-ordered_map_cpp11

# fast build rule for target.
test-ordered_map_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-ordered_map_cpp11.dir/build.make test/CMakeFiles/test-ordered_map_cpp11.dir/build
.PHONY : test-ordered_map_cpp11/fast

#=============================================================================
# Target rules for targets named test-pointer_access_cpp11

# Build rule for target.
test-pointer_access_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-pointer_access_cpp11
.PHONY : test-pointer_access_cpp11

# fast build rule for target.
test-pointer_access_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-pointer_access_cpp11.dir/build.make test/CMakeFiles/test-pointer_access_cpp11.dir/build
.PHONY : test-pointer_access_cpp11/fast

#=============================================================================
# Target rules for targets named test-readme_cpp11

# Build rule for target.
test-readme_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-readme_cpp11
.PHONY : test-readme_cpp11

# fast build rule for target.
test-readme_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-readme_cpp11.dir/build.make test/CMakeFiles/test-readme_cpp11.dir/build
.PHONY : test-readme_cpp11/fast

#=============================================================================
# Target rules for targets named test-reference_access_cpp11

# Build rule for target.
test-reference_access_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-reference_access_cpp11
.PHONY : test-reference_access_cpp11

# fast build rule for target.
test-reference_access_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-reference_access_cpp11.dir/build.make test/CMakeFiles/test-reference_access_cpp11.dir/build
.PHONY : test-reference_access_cpp11/fast

#=============================================================================
# Target rules for targets named test-regression1_cpp11

# Build rule for target.
test-regression1_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-regression1_cpp11
.PHONY : test-regression1_cpp11

# fast build rule for target.
test-regression1_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-regression1_cpp11.dir/build.make test/CMakeFiles/test-regression1_cpp11.dir/build
.PHONY : test-regression1_cpp11/fast

#=============================================================================
# Target rules for targets named test-regression1_cpp17

# Build rule for target.
test-regression1_cpp17: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-regression1_cpp17
.PHONY : test-regression1_cpp17

# fast build rule for target.
test-regression1_cpp17/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-regression1_cpp17.dir/build.make test/CMakeFiles/test-regression1_cpp17.dir/build
.PHONY : test-regression1_cpp17/fast

#=============================================================================
# Target rules for targets named test-regression2_cpp11

# Build rule for target.
test-regression2_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-regression2_cpp11
.PHONY : test-regression2_cpp11

# fast build rule for target.
test-regression2_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-regression2_cpp11.dir/build.make test/CMakeFiles/test-regression2_cpp11.dir/build
.PHONY : test-regression2_cpp11/fast

#=============================================================================
# Target rules for targets named test-regression2_cpp17

# Build rule for target.
test-regression2_cpp17: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-regression2_cpp17
.PHONY : test-regression2_cpp17

# fast build rule for target.
test-regression2_cpp17/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-regression2_cpp17.dir/build.make test/CMakeFiles/test-regression2_cpp17.dir/build
.PHONY : test-regression2_cpp17/fast

#=============================================================================
# Target rules for targets named test-regression2_cpp20

# Build rule for target.
test-regression2_cpp20: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-regression2_cpp20
.PHONY : test-regression2_cpp20

# fast build rule for target.
test-regression2_cpp20/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-regression2_cpp20.dir/build.make test/CMakeFiles/test-regression2_cpp20.dir/build
.PHONY : test-regression2_cpp20/fast

#=============================================================================
# Target rules for targets named test-serialization_cpp11

# Build rule for target.
test-serialization_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-serialization_cpp11
.PHONY : test-serialization_cpp11

# fast build rule for target.
test-serialization_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-serialization_cpp11.dir/build.make test/CMakeFiles/test-serialization_cpp11.dir/build
.PHONY : test-serialization_cpp11/fast

#=============================================================================
# Target rules for targets named test-testsuites_cpp11

# Build rule for target.
test-testsuites_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-testsuites_cpp11
.PHONY : test-testsuites_cpp11

# fast build rule for target.
test-testsuites_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-testsuites_cpp11.dir/build.make test/CMakeFiles/test-testsuites_cpp11.dir/build
.PHONY : test-testsuites_cpp11/fast

#=============================================================================
# Target rules for targets named test-to_chars_cpp11

# Build rule for target.
test-to_chars_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-to_chars_cpp11
.PHONY : test-to_chars_cpp11

# fast build rule for target.
test-to_chars_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-to_chars_cpp11.dir/build.make test/CMakeFiles/test-to_chars_cpp11.dir/build
.PHONY : test-to_chars_cpp11/fast

#=============================================================================
# Target rules for targets named test-ubjson_cpp11

# Build rule for target.
test-ubjson_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-ubjson_cpp11
.PHONY : test-ubjson_cpp11

# fast build rule for target.
test-ubjson_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-ubjson_cpp11.dir/build.make test/CMakeFiles/test-ubjson_cpp11.dir/build
.PHONY : test-ubjson_cpp11/fast

#=============================================================================
# Target rules for targets named test-udt_cpp11

# Build rule for target.
test-udt_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-udt_cpp11
.PHONY : test-udt_cpp11

# fast build rule for target.
test-udt_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-udt_cpp11.dir/build.make test/CMakeFiles/test-udt_cpp11.dir/build
.PHONY : test-udt_cpp11/fast

#=============================================================================
# Target rules for targets named test-udt_macro_cpp11

# Build rule for target.
test-udt_macro_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-udt_macro_cpp11
.PHONY : test-udt_macro_cpp11

# fast build rule for target.
test-udt_macro_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-udt_macro_cpp11.dir/build.make test/CMakeFiles/test-udt_macro_cpp11.dir/build
.PHONY : test-udt_macro_cpp11/fast

#=============================================================================
# Target rules for targets named test-unicode1_cpp11

# Build rule for target.
test-unicode1_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unicode1_cpp11
.PHONY : test-unicode1_cpp11

# fast build rule for target.
test-unicode1_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-unicode1_cpp11.dir/build.make test/CMakeFiles/test-unicode1_cpp11.dir/build
.PHONY : test-unicode1_cpp11/fast

#=============================================================================
# Target rules for targets named test-unicode2_cpp11

# Build rule for target.
test-unicode2_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unicode2_cpp11
.PHONY : test-unicode2_cpp11

# fast build rule for target.
test-unicode2_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-unicode2_cpp11.dir/build.make test/CMakeFiles/test-unicode2_cpp11.dir/build
.PHONY : test-unicode2_cpp11/fast

#=============================================================================
# Target rules for targets named test-unicode3_cpp11

# Build rule for target.
test-unicode3_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unicode3_cpp11
.PHONY : test-unicode3_cpp11

# fast build rule for target.
test-unicode3_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-unicode3_cpp11.dir/build.make test/CMakeFiles/test-unicode3_cpp11.dir/build
.PHONY : test-unicode3_cpp11/fast

#=============================================================================
# Target rules for targets named test-unicode4_cpp11

# Build rule for target.
test-unicode4_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unicode4_cpp11
.PHONY : test-unicode4_cpp11

# fast build rule for target.
test-unicode4_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-unicode4_cpp11.dir/build.make test/CMakeFiles/test-unicode4_cpp11.dir/build
.PHONY : test-unicode4_cpp11/fast

#=============================================================================
# Target rules for targets named test-unicode5_cpp11

# Build rule for target.
test-unicode5_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unicode5_cpp11
.PHONY : test-unicode5_cpp11

# fast build rule for target.
test-unicode5_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-unicode5_cpp11.dir/build.make test/CMakeFiles/test-unicode5_cpp11.dir/build
.PHONY : test-unicode5_cpp11/fast

#=============================================================================
# Target rules for targets named test-user_defined_input_cpp11

# Build rule for target.
test-user_defined_input_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-user_defined_input_cpp11
.PHONY : test-user_defined_input_cpp11

# fast build rule for target.
test-user_defined_input_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-user_defined_input_cpp11.dir/build.make test/CMakeFiles/test-user_defined_input_cpp11.dir/build
.PHONY : test-user_defined_input_cpp11/fast

#=============================================================================
# Target rules for targets named test-wstring_cpp11

# Build rule for target.
test-wstring_cpp11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-wstring_cpp11
.PHONY : test-wstring_cpp11

# fast build rule for target.
test-wstring_cpp11/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test-wstring_cpp11.dir/build.make test/CMakeFiles/test-wstring_cpp11.dir/build
.PHONY : test-wstring_cpp11/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... download_test_data"
	@echo "... test-algorithms_cpp11"
	@echo "... test-allocator_cpp11"
	@echo "... test-alt-string_cpp11"
	@echo "... test-assert_macro_cpp11"
	@echo "... test-bson_cpp11"
	@echo "... test-byte_container_with_subtype_cpp11"
	@echo "... test-capacity_cpp11"
	@echo "... test-cbor_cpp11"
	@echo "... test-class_const_iterator_cpp11"
	@echo "... test-class_iterator_cpp11"
	@echo "... test-class_lexer_cpp11"
	@echo "... test-class_parser_cpp11"
	@echo "... test-comparison_cpp11"
	@echo "... test-comparison_cpp20"
	@echo "... test-concepts_cpp11"
	@echo "... test-constructor1_cpp11"
	@echo "... test-constructor2_cpp11"
	@echo "... test-convenience_cpp11"
	@echo "... test-conversions_cpp11"
	@echo "... test-conversions_cpp14"
	@echo "... test-conversions_cpp17"
	@echo "... test-deserialization_cpp11"
	@echo "... test-diagnostics_cpp11"
	@echo "... test-disabled_exceptions_cpp11"
	@echo "... test-element_access1_cpp11"
	@echo "... test-element_access2_cpp11"
	@echo "... test-hash_cpp11"
	@echo "... test-inspection_cpp11"
	@echo "... test-items_cpp11"
	@echo "... test-items_cpp14"
	@echo "... test-items_cpp17"
	@echo "... test-iterators1_cpp11"
	@echo "... test-iterators2_cpp11"
	@echo "... test-json_patch_cpp11"
	@echo "... test-json_pointer_cpp11"
	@echo "... test-large_json_cpp11"
	@echo "... test-merge_patch_cpp11"
	@echo "... test-meta_cpp11"
	@echo "... test-modifiers_cpp11"
	@echo "... test-msgpack_cpp11"
	@echo "... test-noexcept_cpp11"
	@echo "... test-ordered_json_cpp11"
	@echo "... test-ordered_map_cpp11"
	@echo "... test-pointer_access_cpp11"
	@echo "... test-readme_cpp11"
	@echo "... test-reference_access_cpp11"
	@echo "... test-regression1_cpp11"
	@echo "... test-regression1_cpp17"
	@echo "... test-regression2_cpp11"
	@echo "... test-regression2_cpp17"
	@echo "... test-regression2_cpp20"
	@echo "... test-serialization_cpp11"
	@echo "... test-testsuites_cpp11"
	@echo "... test-to_chars_cpp11"
	@echo "... test-ubjson_cpp11"
	@echo "... test-udt_cpp11"
	@echo "... test-udt_macro_cpp11"
	@echo "... test-unicode1_cpp11"
	@echo "... test-unicode2_cpp11"
	@echo "... test-unicode3_cpp11"
	@echo "... test-unicode4_cpp11"
	@echo "... test-unicode5_cpp11"
	@echo "... test-user_defined_input_cpp11"
	@echo "... test-wstring_cpp11"
	@echo "... test_main"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

