"""Automatically generated source lists for nlohmann_json - DO NOT EDIT."""

nlohmann_json_hdrs = [
    "nlohmann/adl_serializer.hpp",
    "nlohmann/json_fwd.hpp",
    "nlohmann/thirdparty/hedley/hedley_undef.hpp",
    "nlohmann/thirdparty/hedley/hedley.hpp",
    "nlohmann/json.hpp",
    "nlohmann/detail/json_pointer.hpp",
    "nlohmann/detail/value_t.hpp",
    "nlohmann/detail/input/json_sax.hpp",
    "nlohmann/detail/input/lexer.hpp",
    "nlohmann/detail/input/input_adapters.hpp",
    "nlohmann/detail/input/position_t.hpp",
    "nlohmann/detail/input/binary_reader.hpp",
    "nlohmann/detail/input/parser.hpp",
    "nlohmann/detail/iterators/internal_iterator.hpp",
    "nlohmann/detail/iterators/iteration_proxy.hpp",
    "nlohmann/detail/iterators/json_reverse_iterator.hpp",
    "nlohmann/detail/iterators/iterator_traits.hpp",
    "nlohmann/detail/iterators/iter_impl.hpp",
    "nlohmann/detail/iterators/primitive_iterator.hpp",
    "nlohmann/detail/json_ref.hpp",
    "nlohmann/detail/macro_scope.hpp",
    "nlohmann/detail/macro_unscope.hpp",
    "nlohmann/detail/exceptions.hpp",
    "nlohmann/detail/output/output_adapters.hpp",
    "nlohmann/detail/output/serializer.hpp",
    "nlohmann/detail/output/binary_writer.hpp",
    "nlohmann/detail/conversions/from_json.hpp",
    "nlohmann/detail/conversions/to_chars.hpp",
    "nlohmann/detail/conversions/to_json.hpp",
    "nlohmann/detail/meta/void_t.hpp",
    "nlohmann/detail/meta/cpp_future.hpp",
    "nlohmann/detail/meta/detected.hpp",
    "nlohmann/detail/meta/is_sax.hpp",
    "nlohmann/detail/meta/type_traits.hpp",
]

nlohmann_json_srcs = [
]
