package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "nlohmann_json_test",
    srcs = [
        "main.cpp",
    ],
    deps = [
        "@com_github_nlohmann_json//:nlohmann_json",
    ],
)
