name: "Pull Request Labeler"

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: srvaroa/labeler@e8fbb2561481ef6e711a770f0234e9379dc76892 # master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
